ALTER TABLE "warehouse_staff" ADD COLUMN "id" UUID NULL DEFAULT gen_random_uuid();
ALTER TABLE "warehouse_staff" ADD COLUMN "user_id" UUID NOT NULL;
ALTER TABLE "warehouse_staff" ADD COLUMN "position" VARCHAR(255) NOT NULL;
ALTER TABLE "warehouse_staff" ADD COLUMN "start_date" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "warehouse_staff" ADD COLUMN "end_date" TIMESTAMP NULL;
ALTER TABLE "warehouse_staff" ADD COLUMN "is_primary" BOOLEAN NULL DEFAULT false;
ALTER TABLE "branch_staff" ADD COLUMN "id" UUID NULL DEFAULT gen_random_uuid();
ALTER TABLE "branch_staff" ADD COLUMN "user_id" UUID NOT NULL;
ALTER TABLE "branch_staff" ADD COLUMN "position" VARCHAR(255) NOT NULL;
ALTER TABLE "branch_staff" ADD COLUMN "start_date" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "branch_staff" ADD COLUMN "end_date" TIMESTAMP NULL;
ALTER TABLE "branch_staff" ADD COLUMN "is_primary" BOOLEAN NULL DEFAULT false;
ALTER TABLE "inventory_zones" ADD COLUMN "warehouse_id" UUID NOT NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "zone_name" VARCHAR(255) NOT NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "zone_code" VARCHAR(255) NOT NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "capacity" INTEGER NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "zone_type" VARCHAR(255) NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "aisles" VARCHAR(255) NULL;
ALTER TABLE "inventory_zones" ADD COLUMN "warehouse_id" UUID NULL;
ALTER TABLE "branch_targets" ADD COLUMN "target_type" VARCHAR(50) NOT NULL;
ALTER TABLE "branch_targets" ADD COLUMN "target_value" DECIMAL(10,2) NOT NULL;
ALTER TABLE "branch_targets" ADD COLUMN "achieved_value" DECIMAL(10,2) NULL DEFAULT 0;
ALTER TABLE "repairs" ADD COLUMN "repair_type" VARCHAR(255) NOT NULL;
ALTER TABLE "repairs" ADD COLUMN "cost" DECIMAL(10,2) NULL DEFAULT 0;
ALTER TABLE "repairs" ADD COLUMN "start_time" TIMESTAMP NULL;
ALTER TABLE "repairs" ADD COLUMN "end_time" TIMESTAMP NULL;
ALTER TABLE "job_sheet_parts" ADD COLUMN "warranty_months" INTEGER NULL DEFAULT 0;
ALTER TABLE "job_sheet_products" ADD COLUMN "cost_price" DECIMAL(10,2) NOT NULL;
ALTER TABLE "job_sheet_products" ADD COLUMN "warranty_months" INTEGER NULL DEFAULT 0;
ALTER TABLE "job_sheet_products" ADD COLUMN "serial_number" VARCHAR(255) NULL;
ALTER TABLE "job_sheet_products" ADD COLUMN "batch_number" VARCHAR(255) NULL;
ALTER TABLE "job_sheet_products" ADD COLUMN "status" VARCHAR(50) NULL DEFAULT 'PENDING';
ALTER TABLE "job_sheet_products" ADD COLUMN "installed_date" TIMESTAMP NULL;
ALTER TABLE "job_sheet_products" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "parts" ADD COLUMN "part_number" VARCHAR(255) NOT NULL;
ALTER TABLE "parts" ADD COLUMN "category" VARCHAR(50) NOT NULL;
ALTER TABLE "parts" ADD COLUMN "brand" VARCHAR(255) NULL;
ALTER TABLE "parts" ADD COLUMN "model" VARCHAR(255) NULL;
ALTER TABLE "parts" ADD COLUMN "compatibility" TEXT NULL;
ALTER TABLE "parts" ADD COLUMN "cost_price" DECIMAL(10,2) NOT NULL;
ALTER TABLE "parts" ADD COLUMN "reorder_level" INTEGER NULL DEFAULT 10;
ALTER TABLE "parts" ADD COLUMN "supplier" VARCHAR(255) NULL;
ALTER TABLE "parts" ADD COLUMN "supplier_contact" VARCHAR(255) NULL;
ALTER TABLE "parts" ADD COLUMN "warranty_months" INTEGER NULL DEFAULT 0;
ALTER TABLE "stock_movements" ADD COLUMN "part_id" UUID NOT NULL;
ALTER TABLE "stock_movements" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "stock_movements" ADD COLUMN "part_id" UUID NULL;
ALTER TABLE "payments" ADD COLUMN "received_by_id" UUID NULL;
ALTER TABLE "sale_payments" ADD COLUMN "payment_number" VARCHAR(255) NOT NULL;
ALTER TABLE "sale_refunds" ADD COLUMN "processed_by_id" UUID NOT NULL;
ALTER TABLE "sale_refunds" ADD COLUMN "processed_by_id" UUID NULL;
ALTER TABLE "supplier_products" ADD COLUMN "moq" INTEGER NULL DEFAULT 1;
ALTER TABLE "supplier_products" ADD COLUMN "is_primary" BOOLEAN NULL DEFAULT false;
ALTER TABLE "supplier_products" ADD COLUMN "last_purchase_date" TIMESTAMP NULL;
ALTER TABLE "supplier_products" ADD COLUMN "last_purchase_price" DECIMAL(10,2) NULL;
ALTER TABLE "supplier_products" ADD COLUMN "is_active" BOOLEAN NULL DEFAULT true;
ALTER TABLE "supplier_returns" ADD COLUMN "return_type" VARCHAR(50) NOT NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "reason_description" TEXT NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "refund_amount" DECIMAL(10,2) NULL DEFAULT 0;
ALTER TABLE "supplier_returns" ADD COLUMN "refund_method" VARCHAR(50) NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "refund_date" TIMESTAMP NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "replacement_issued" BOOLEAN NULL DEFAULT false;
ALTER TABLE "supplier_returns" ADD COLUMN "approved_by" VARCHAR(255) NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "approved_at" TIMESTAMP NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "supplier_returns" ADD COLUMN "attachments" VARCHAR(255) NULL;
ALTER TABLE "supplier_return_items" ADD COLUMN "batch_number" VARCHAR(255) NULL;
ALTER TABLE "supplier_return_items" ADD COLUMN "serial_number" VARCHAR(255) NULL;
ALTER TABLE "supplier_return_items" ADD COLUMN "condition" VARCHAR(255) NULL;
ALTER TABLE "supplier_return_items" ADD COLUMN "images" VARCHAR(255) NULL;
ALTER TABLE "supplier_return_items" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "stock_releases" ADD COLUMN "release_type" VARCHAR(50) NOT NULL;
ALTER TABLE "stock_releases" ADD COLUMN "reference_id" VARCHAR(255) NULL;
ALTER TABLE "stock_releases" ADD COLUMN "reference_type" VARCHAR(255) NULL;
ALTER TABLE "stock_releases" ADD COLUMN "reference_number" VARCHAR(255) NULL;
ALTER TABLE "stock_releases" ADD COLUMN "requested_by" VARCHAR(255) NULL;
ALTER TABLE "stock_releases" ADD COLUMN "approved_by" VARCHAR(255) NULL;
ALTER TABLE "stock_releases" ADD COLUMN "approved_at" TIMESTAMP NULL;
ALTER TABLE "stock_releases" ADD COLUMN "released_at" TIMESTAMP NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "requested_quantity" INTEGER NOT NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "released_quantity" INTEGER NULL DEFAULT 0;
ALTER TABLE "stock_release_items" ADD COLUMN "unit_cost" DECIMAL(10,2) NOT NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "total_cost" DECIMAL(10,2) NOT NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "serial_number" VARCHAR(255) NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "location" VARCHAR(255) NULL;
ALTER TABLE "stock_release_items" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "zone_code" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "aisle" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "rack" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "shelf" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "bin_location" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "batches" VARCHAR(255) NULL;
ALTER TABLE "warehouse_inventory" ADD COLUMN "last_restocked" TIMESTAMP NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "from_location_id" UUID NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "to_location_id" UUID NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "transfer_type" VARCHAR(50) NOT NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "requested_by" VARCHAR(255) NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "approved_by" VARCHAR(255) NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "approved_at" TIMESTAMP NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "sent_by" VARCHAR(255) NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "sent_at" TIMESTAMP NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "received_by" VARCHAR(255) NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "received_at" TIMESTAMP NULL;
ALTER TABLE "stock_transfers" ADD COLUMN "attachments" VARCHAR(255) NULL;
ALTER TABLE "stock_transfer_items" ADD COLUMN "requested_quantity" INTEGER NOT NULL;
ALTER TABLE "stock_transfer_items" ADD COLUMN "sent_quantity" INTEGER NULL DEFAULT 0;
ALTER TABLE "stock_transfer_items" ADD COLUMN "received_quantity" INTEGER NULL DEFAULT 0;
ALTER TABLE "stock_transfer_items" ADD COLUMN "notes" TEXT NULL;
ALTER TABLE "notifications" ADD COLUMN "job_sheet_id" UUID NULL;
ALTER TABLE "notifications" ADD COLUMN "recipient" VARCHAR(255) NULL;
ALTER TABLE "notifications" ADD COLUMN "method" VARCHAR(50) NOT NULL;
ALTER TABLE "notifications" ADD COLUMN "status" VARCHAR(50) NULL DEFAULT 'PENDING';
ALTER TABLE "notifications" ADD COLUMN "sent_at" TIMESTAMP NULL;
ALTER TABLE "notifications" ADD COLUMN "job_sheet_id" UUID NULL;
ALTER TABLE "activity_logs" ADD COLUMN "user_name" VARCHAR(255) NULL;
ALTER TABLE "activity_logs" ADD COLUMN "module" VARCHAR(255) NOT NULL;
ALTER TABLE "activity_logs" ADD COLUMN "record_id" VARCHAR(255) NULL;
ALTER TABLE "activity_logs" ADD COLUMN "details" VARCHAR(255) NULL;
ALTER TABLE "sms_logs" ADD COLUMN "type" VARCHAR(50) NOT NULL;
ALTER TABLE "sms_logs" ADD COLUMN "recipient" VARCHAR(255) NOT NULL;
ALTER TABLE "sms_logs" ADD COLUMN "response" TEXT NULL;
ALTER TABLE "role_permissions" ADD COLUMN "id" UUID NULL DEFAULT gen_random_uuid();