-- Auto-generated SQL to fix missing columns

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS staff TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS received_payments TEXT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_logs TEXT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notifications TEXT NOT NULL;

-- locations
ALTER TABLE locations ADD COLUMN IF NOT EXISTS customers TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS job_sheets TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS inventory TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS product_inventory TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS sales TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS goods_receipts TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS warranty_cards TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS warranty_claims TEXT NOT NULL;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS product_returns TEXT NOT NULL;

-- branches
ALTER TABLE branches ADD COLUMN IF NOT EXISTS branch_staff TEXT NOT NULL;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS branch_targets TEXT NOT NULL;

-- warehouse_staff
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS id VARCHAR(255) NOT NULL DEFAULT 'uuid(';
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) NOT NULL;
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS position VARCHAR(255) NOT NULL;
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now(';
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE warehouse_staff ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT false;

-- branch_staff
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS id VARCHAR(255) NOT NULL DEFAULT 'uuid(';
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) NOT NULL;
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS position VARCHAR(255) NOT NULL;
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now(';
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE branch_staff ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT false;

-- inventory_zones
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS warehouse_id VARCHAR(255) NOT NULL;
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS zone_name VARCHAR(255) NOT NULL;
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS zone_code VARCHAR(255) NOT NULL;
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS capacity INTEGER;
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS zone_type VARCHAR(255);
ALTER TABLE inventory_zones ADD COLUMN IF NOT EXISTS aisles JSONB;

-- stock_transfers
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS from_location_id VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS to_location_id VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS transfer_type TEXT NOT NULL;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS requested_by VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS sent_by VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS received_by VARCHAR(255);
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS received_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS attachments JSONB;
ALTER TABLE stock_transfers ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;

-- stock_transfer_items
ALTER TABLE stock_transfer_items ADD COLUMN IF NOT EXISTS requested_quantity INTEGER NOT NULL;
ALTER TABLE stock_transfer_items ADD COLUMN IF NOT EXISTS sent_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE stock_transfer_items ADD COLUMN IF NOT EXISTS received_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE stock_transfer_items ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- branch_targets
ALTER TABLE branch_targets ADD COLUMN IF NOT EXISTS target_type TEXT NOT NULL;
ALTER TABLE branch_targets ADD COLUMN IF NOT EXISTS target_value DECIMAL(12,2) NOT NULL;
ALTER TABLE branch_targets ADD COLUMN IF NOT EXISTS achieved_value DECIMAL(12,2) NOT NULL DEFAULT 0;

-- roles
ALTER TABLE roles ADD COLUMN IF NOT EXISTS users TEXT NOT NULL;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS permissions TEXT NOT NULL;

-- permissions
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS roles TEXT NOT NULL;

-- customers
ALTER TABLE customers ADD COLUMN IF NOT EXISTS devices TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS job_sheets TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS payments TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS notifications TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS sales TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS warranty_cards TEXT NOT NULL;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS product_returns TEXT NOT NULL;

-- devices
ALTER TABLE devices ADD COLUMN IF NOT EXISTS job_sheets TEXT NOT NULL;

-- job_sheets
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS repairs TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS parts TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS products TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS payments TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS status_history TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS notifications TEXT NOT NULL;
ALTER TABLE job_sheets ADD COLUMN IF NOT EXISTS warranty_claim TEXT;

-- repairs
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS repair_type VARCHAR(255) NOT NULL;
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS cost DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE;

-- parts
ALTER TABLE parts ADD COLUMN IF NOT EXISTS part_number VARCHAR(255) NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS category TEXT NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS brand VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS model VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS compatibility VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS cost_price DECIMAL(12,2) NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS reorder_level INTEGER NOT NULL DEFAULT 10;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS supplier VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS supplier_contact VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS warranty_months INTEGER NOT NULL DEFAULT 0;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS inventory TEXT NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS job_sheet_parts TEXT NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS stock_movements TEXT NOT NULL;

-- job_sheet_parts
ALTER TABLE job_sheet_parts ADD COLUMN IF NOT EXISTS warranty_months INTEGER NOT NULL DEFAULT 0;

-- stock_movements
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS part_id VARCHAR(255) NOT NULL;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS received_by_id VARCHAR(255) NOT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reference VARCHAR(255);

-- job_status_history
ALTER TABLE job_status_history ADD COLUMN IF NOT EXISTS changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT 'now(';
ALTER TABLE job_status_history ADD COLUMN IF NOT EXISTS remarks VARCHAR(255);

-- notifications
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS job_sheet_id VARCHAR(255);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS method TEXT NOT NULL;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS recipient VARCHAR(255) NOT NULL;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE;

-- notification_settings
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS admin_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS manager_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS customer_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS staff_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS sms_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS email_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS whatsapp_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS auto_send BOOLEAN NOT NULL DEFAULT true;

-- activity_logs
ALTER TABLE activity_logs ADD COLUMN IF NOT EXISTS module VARCHAR(255) NOT NULL;
ALTER TABLE activity_logs ADD COLUMN IF NOT EXISTS record_id VARCHAR(255);
ALTER TABLE activity_logs ADD COLUMN IF NOT EXISTS details JSONB;

-- product_categories
ALTER TABLE product_categories ADD COLUMN IF NOT EXISTS products TEXT NOT NULL;

-- products
ALTER TABLE products ADD COLUMN IF NOT EXISTS compatibility VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS inventory TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier_products TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS purchase_order_items TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_movements TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS job_sheet_products TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_releases TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sale_items TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_cards TEXT NOT NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_returns TEXT NOT NULL;

-- suppliers
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS supplier_products TEXT NOT NULL;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS purchase_orders TEXT NOT NULL;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS supplier_returns TEXT NOT NULL;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS supplier_payments TEXT NOT NULL;

-- supplier_products
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS supplier_s_k_u VARCHAR(255);
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS moq INTEGER NOT NULL DEFAULT 1;
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS last_purchase_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS last_purchase_price DECIMAL(12,2);
ALTER TABLE supplier_products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

-- purchase_orders
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS receipts TEXT NOT NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS payments TEXT NOT NULL;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS status_history TEXT NOT NULL;

-- goods_receipts
ALTER TABLE goods_receipts ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;

-- supplier_returns
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS return_type TEXT NOT NULL;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS reason_description VARCHAR(255);
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS refund_amount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS refund_method TEXT;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS refund_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS replacement_issued BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS notes VARCHAR(255);
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS attachments JSONB;
ALTER TABLE supplier_returns ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;

-- supplier_return_items
ALTER TABLE supplier_return_items ADD COLUMN IF NOT EXISTS batch_number VARCHAR(255);
ALTER TABLE supplier_return_items ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);
ALTER TABLE supplier_return_items ADD COLUMN IF NOT EXISTS condition VARCHAR(255);
ALTER TABLE supplier_return_items ADD COLUMN IF NOT EXISTS images JSONB;
ALTER TABLE supplier_return_items ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- supplier_payments
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS reference VARCHAR(255);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS check_number VARCHAR(255);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS attachments JSONB;
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS paid_by VARCHAR(255);

-- product_stock_movements
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS product_id VARCHAR(255) NOT NULL;
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS location_id VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS quantity_before INTEGER NOT NULL;
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS quantity_after INTEGER NOT NULL;
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS reference_number VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(12,2);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS total_cost DECIMAL(12,2);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS batch_number VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS performed_by VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE product_stock_movements ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- stock_releases
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS release_type TEXT NOT NULL;
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS reference_id VARCHAR(255);
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS reference_type VARCHAR(255);
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS reference_number VARCHAR(255);
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS requested_by VARCHAR(255);
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255);
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS released_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_releases ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;

-- stock_release_items
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS requested_quantity INTEGER NOT NULL;
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS released_quantity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(12,2) NOT NULL;
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS total_cost DECIMAL(12,2) NOT NULL;
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE stock_release_items ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- job_sheet_products
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS cost_price DECIMAL(12,2) NOT NULL;
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS warranty_months INTEGER NOT NULL DEFAULT 0;
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS batch_number VARCHAR(255);
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS installed_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE job_sheet_products ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- sales
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS sale_channel VARCHAR(255) DEFAULT '"POS"';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_type TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_reason VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS invoice_url VARCHAR(255);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS items TEXT NOT NULL;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS payments TEXT NOT NULL;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS refunds TEXT NOT NULL;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS warranty_cards TEXT NOT NULL;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS notifications TEXT NOT NULL;

-- sale_items
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS product_name VARCHAR(255) NOT NULL;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS product_s_k_u VARCHAR(255);
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS cost_price DECIMAL(12,2) NOT NULL;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS discount DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS warranty_card TEXT;

-- sale_payments
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS payment_number VARCHAR(255) NOT NULL;
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS reference VARCHAR(255);
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS received_by_id VARCHAR(255) NOT NULL;

-- sale_refunds
ALTER TABLE sale_refunds ADD COLUMN IF NOT EXISTS processed_by_id VARCHAR(255) NOT NULL;

-- warranty_cards
ALTER TABLE warranty_cards ADD COLUMN IF NOT EXISTS product_s_k_u VARCHAR(255);
ALTER TABLE warranty_cards ADD COLUMN IF NOT EXISTS claims TEXT NOT NULL;

-- sms_logs
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS type TEXT NOT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS recipient VARCHAR(255) NOT NULL;
ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS response VARCHAR(255);

-- product_returns
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS source_id VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS return_reason VARCHAR(255) NOT NULL;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS return_category TEXT NOT NULL;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS condition_notes VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS inspected_by VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS inspected_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS inspection_notes VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS approval_notes VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS resolution_type TEXT;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS resolution_details VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS resolution_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS sale_refund_id VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS supplier_return_id VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS stock_transfer_id VARCHAR(255);
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS documents JSONB;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_returns ADD COLUMN IF NOT EXISTS notifications TEXT NOT NULL;