/**
 * Enum definitions for Sequelize models
 * These correspond to the Prisma schema enums
 */

// Location Management
export enum LocationType {
  WAREHOUSE = 'WAREHOUSE',
  BRANCH = 'BRANCH',
  STORE = 'STORE',
  OUTLET = 'OUTLET'
}

export enum WarehouseType {
  GENERAL = 'GENERAL',
  ELECTRONICS = 'ELECTRONICS',
  PARTS = 'PARTS',
  BULK = 'BULK',
  COLD_STORAGE = 'COLD_STORAGE',
  SECURE = 'SECURE'
}

export enum BranchType {
  SERVICE_CENTER = 'SERVICE_CENTER',
  SALES_OUTLET = 'SALES_OUTLET',
  SHOWROOM = 'SHOWROOM',
  FULL_SERVICE = 'FULL_SERVICE',
  FRANCHISE = 'FRANCHISE',
  AUTHORIZED_CENTER = 'AUTHORIZED_CENTER'
}

export enum TargetType {
  SALES = 'SALES',
  REPAIR = 'REPAIR',
  REVENUE = 'REVENUE',
  CUSTOMER_ACQUISITION = 'CUSTOMER_ACQUISITION'
}

// Customer Management
export enum CustomerType {
  WALK_IN = 'WALK_IN',
  REGULAR = 'REGULAR',
  VIP = 'VIP'
}

// Device Management
export enum DeviceType {
  MOBILE = 'MOBILE',
  TABLET = 'TABLET',
  LAPTOP = 'LAPTOP',
  DESKTOP = 'DESKTOP',
  SMARTWATCH = 'SMARTWATCH',
  OTHER = 'OTHER'
}

// Job Sheet Management
export enum JobStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_PARTS = 'WAITING_PARTS',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  COMPLETED = 'COMPLETED',
  QUALITY_CHECK = 'QUALITY_CHECK',
  READY_DELIVERY = 'READY_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD'
}

export enum Priority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum RepairStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

// Parts & Inventory
export enum PartCategory {
  SCREEN = 'SCREEN',
  BATTERY = 'BATTERY',
  CHARGER = 'CHARGER',
  BACK_COVER = 'BACK_COVER',
  CAMERA = 'CAMERA',
  SPEAKER = 'SPEAKER',
  MICROPHONE = 'MICROPHONE',
  CHARGING_PORT = 'CHARGING_PORT',
  HEADPHONE_JACK = 'HEADPHONE_JACK',
  BUTTON = 'BUTTON',
  FLEX_CABLE = 'FLEX_CABLE',
  MOTHERBOARD = 'MOTHERBOARD',
  RAM = 'RAM',
  STORAGE = 'STORAGE',
  OTHER = 'OTHER'
}

export enum MovementType {
  IN = 'IN',
  OUT = 'OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  RETURN = 'RETURN',
  DAMAGED = 'DAMAGED'
}

// Payment
export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_PAYMENT = 'MOBILE_PAYMENT',
  CHECK = 'CHECK',
  OTHER = 'OTHER'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED'
}

// Notifications
export enum RecipientType {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  STAFF = 'STAFF',
  TECHNICIAN = 'TECHNICIAN',
  SYSTEM = 'SYSTEM'
}

export enum EventType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  PRICE_UPDATE = 'PRICE_UPDATE',
  QUANTITY_UPDATE = 'QUANTITY_UPDATE',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
  ASSIGNMENT = 'ASSIGNMENT',
  COMPLETION = 'COMPLETION'
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum NotificationType {
  // Job Sheet
  JOB_CREATED = 'JOB_CREATED',
  JOB_STARTED = 'JOB_STARTED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_UPDATED = 'JOB_UPDATED',
  JOB_DELETED = 'JOB_DELETED',
  JOB_STATUS_CHANGED = 'JOB_STATUS_CHANGED',
  JOB_ASSIGNED = 'JOB_ASSIGNED',
  READY_PICKUP = 'READY_PICKUP',
  JOB_READY_PICKUP = 'JOB_READY_PICKUP',
  JOB_DIAGNOSED = 'JOB_DIAGNOSED',
  JOB_REPAIRING = 'JOB_REPAIRING',
  JOB_DELIVERED = 'JOB_DELIVERED',
  JOB_CANCELLED = 'JOB_CANCELLED',
  JOB_PRICE_UPDATED = 'JOB_PRICE_UPDATED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  JOB_REMINDER = 'JOB_REMINDER',
  
  // Sales
  SALE_CREATED = 'SALE_CREATED',
  SALE_COMPLETED = 'SALE_COMPLETED',
  SALE_UPDATED = 'SALE_UPDATED',
  SALE_CANCELLED = 'SALE_CANCELLED',
  SALE_PRICE_CHANGED = 'SALE_PRICE_CHANGED',
  SALE_PAYMENT_RECEIVED = 'SALE_PAYMENT_RECEIVED',
  SALE_RECEIPT = 'SALE_RECEIPT',
  SALE_HIGH_VALUE = 'SALE_HIGH_VALUE',
  
  // Product Returns
  RETURN_CREATED = 'RETURN_CREATED',
  RETURN_RECEIVED = 'RETURN_RECEIVED',
  RETURN_INSPECTED = 'RETURN_INSPECTED',
  RETURN_APPROVED = 'RETURN_APPROVED',
  RETURN_REJECTED = 'RETURN_REJECTED',
  RETURN_COMPLETED = 'RETURN_COMPLETED',
  RETURN_REFUNDED = 'RETURN_REFUNDED',
  RETURN_REPLACED = 'RETURN_REPLACED',
  RETURN_UPDATED = 'RETURN_UPDATED',
  RETURN_CANCELLED = 'RETURN_CANCELLED',
  
  // Addon Requests
  ADDON_REQUEST_CREATED = 'ADDON_REQUEST_CREATED',
  ADDON_REQUEST_APPROVED = 'ADDON_REQUEST_APPROVED',
  ADDON_REQUEST_REJECTED = 'ADDON_REQUEST_REJECTED',
  ADDON_REQUEST_COMPLETED = 'ADDON_REQUEST_COMPLETED',
  
  // General
  REMINDER = 'REMINDER',
  PROMOTION = 'PROMOTION'
}

export enum NotificationMethod {
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP'
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  DELIVERED = 'DELIVERED'
}

// Products
export enum WarrantyType {
  STANDARD = 'STANDARD',
  EXTENDED = 'EXTENDED',
  LIMITED = 'LIMITED',
  LIFETIME = 'LIFETIME',
  NO_WARRANTY = 'NO_WARRANTY'
}

export enum QualityGrade {
  A_GRADE = 'A_GRADE',
  B_GRADE = 'B_GRADE',
  C_GRADE = 'C_GRADE',
  OEM = 'OEM',
  AFTERMARKET = 'AFTERMARKET'
}

// Suppliers
export enum SupplierType {
  LOCAL = 'LOCAL',
  INTERNATIONAL = 'INTERNATIONAL',
  MANUFACTURER = 'MANUFACTURER',
  DISTRIBUTOR = 'DISTRIBUTOR',
  WHOLESALER = 'WHOLESALER',
  RETAILER = 'RETAILER'
}

export enum SupplierStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLACKLISTED = 'BLACKLISTED',
  PENDING_APPROVAL = 'PENDING_APPROVAL'
}

// Stock Transfer
export enum TransferType {
  WAREHOUSE_TO_WAREHOUSE = 'WAREHOUSE_TO_WAREHOUSE',
  WAREHOUSE_TO_BRANCH = 'WAREHOUSE_TO_BRANCH',
  BRANCH_TO_BRANCH = 'BRANCH_TO_BRANCH',
  BRANCH_TO_WAREHOUSE = 'BRANCH_TO_WAREHOUSE'
}

export enum TransferStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

// Purchase Orders
export enum POStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  CONFIRMED = 'CONFIRMED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD'
}

export enum POPaymentStatus {
  UNPAID = 'UNPAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERPAID = 'OVERPAID'
}

export enum GRNStatus {
  PENDING_QC = 'PENDING_QC',
  QC_PASSED = 'QC_PASSED',
  QC_FAILED = 'QC_FAILED',
  PARTIALLY_ACCEPTED = 'PARTIALLY_ACCEPTED',
  COMPLETED = 'COMPLETED'
}

export enum ItemQualityStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  DAMAGED = 'DAMAGED',
  PARTIAL = 'PARTIAL'
}

// Returns
export enum ReturnType {
  DAMAGED = 'DAMAGED',
  DEFECTIVE = 'DEFECTIVE',
  WRONG_ITEM = 'WRONG_ITEM',
  EXCESS_QUANTITY = 'EXCESS_QUANTITY',
  WARRANTY_CLAIM = 'WARRANTY_CLAIM',
  OTHER = 'OTHER'
}

export enum ReturnReason {
  DOA = 'DOA',
  MANUFACTURING_DEFECT = 'MANUFACTURING_DEFECT',
  SHIPPING_DAMAGE = 'SHIPPING_DAMAGE',
  WRONG_SPECIFICATION = 'WRONG_SPECIFICATION',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  EXPIRED = 'EXPIRED',
  PACKAGING_DAMAGED = 'PACKAGING_DAMAGED',
  INCOMPLETE = 'INCOMPLETE',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  DEFECTIVE = 'DEFECTIVE',
  WRONG_ITEM = 'WRONG_ITEM',
  CUSTOMER_CHANGED_MIND = 'CUSTOMER_CHANGED_MIND',
  SIZE_COLOR_ISSUE = 'SIZE_COLOR_ISSUE',
  DAMAGED_IN_SHIPPING = 'DAMAGED_IN_SHIPPING',
  EXCESS_STOCK = 'EXCESS_STOCK',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',
  USER_DAMAGE = 'USER_DAMAGE',
  OTHER = 'OTHER'
}

export enum ReturnStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED = 'RECEIVED',
  INSPECTING = 'INSPECTING',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  REPLACEMENT_SENT = 'REPLACEMENT_SENT',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PROCESSING = 'PROCESSING'
}

export enum RefundMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_NOTE = 'CREDIT_NOTE',
  REPLACEMENT = 'REPLACEMENT',
  ACCOUNT_CREDIT = 'ACCOUNT_CREDIT'
}

// Stock Management
export enum StockMovementType {
  PURCHASE = 'PURCHASE',
  SALES = 'SALES',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
  RETURN_FROM_CUSTOMER = 'RETURN_FROM_CUSTOMER',
  RETURN_TO_SUPPLIER = 'RETURN_TO_SUPPLIER',
  DAMAGED = 'DAMAGED',
  EXPIRED = 'EXPIRED',
  STOLEN = 'STOLEN',
  FOUND = 'FOUND',
  USAGE = 'USAGE',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
  WRITE_OFF = 'WRITE_OFF'
}

export enum ReferenceType {
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  JOB_SHEET = 'JOB_SHEET',
  TRANSFER = 'TRANSFER',           // From Prisma schema
  STOCK_TRANSFER = 'STOCK_TRANSFER', // Alternative naming
  RETURN = 'RETURN',
  ADJUSTMENT = 'ADJUSTMENT',
  GOODS_RECEIPT = 'GOODS_RECEIPT',
  STOCK_RELEASE = 'STOCK_RELEASE',
  SALE = 'SALE',
  SALE_REFUND = 'SALE_REFUND'
}

export enum ReleaseType {
  JOB_USAGE = 'JOB_USAGE',
  BRANCH_TRANSFER = 'BRANCH_TRANSFER',
  INTERNAL_USE = 'INTERNAL_USE',
  SAMPLE = 'SAMPLE',
  PROMOTION = 'PROMOTION',
  DISPOSAL = 'DISPOSAL',
  OTHER = 'OTHER'
}

export enum ReleaseStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  RELEASED = 'RELEASED',
  RECEIVED = 'RECEIVED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum JobProductStatus {
  PENDING = 'PENDING',
  RESERVED = 'RESERVED',
  INSTALLED = 'INSTALLED',
  RETURNED = 'RETURNED',
  DEFECTIVE = 'DEFECTIVE'
}

// Sales
export enum SaleType {
  DIRECT = 'DIRECT',      // Direct sale (Prisma)
  ONLINE = 'ONLINE',      // Online sale (Prisma)
  PHONE = 'PHONE',        // Phone order (Prisma)
  WHOLESALE = 'WHOLESALE', // Wholesale (Prisma)
  RETAIL = 'RETAIL',      // Legacy - keep for backward compatibility
  POS = 'POS'             // Legacy - keep for backward compatibility
}

export enum SaleStatus {
  DRAFT = 'DRAFT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIAL_REFUND = 'PARTIAL_REFUND'
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED'
}

// Warranty
export enum WarrantyStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CLAIMED = 'CLAIMED',
  VOIDED = 'VOIDED',
  TRANSFERRED = 'TRANSFERRED'
}

export enum ClaimStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum ClaimPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum ResolutionType {
  REPAIRED = 'REPAIRED',
  REPLACED = 'REPLACED',
  REFUNDED = 'REFUNDED',
  STORE_CREDIT = 'STORE_CREDIT',
  REJECTED = 'REJECTED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  RESTOCKED_BRANCH = 'RESTOCKED_BRANCH',
  TRANSFERRED_WAREHOUSE = 'TRANSFERRED_WAREHOUSE',
  RETURNED_SUPPLIER = 'RETURNED_SUPPLIER',
  SCRAPPED = 'SCRAPPED',
  PENDING_DECISION = 'PENDING_DECISION'
}

// SMS
export enum SMSTemplateType {
  SALE_CONFIRMATION = 'SALE_CONFIRMATION',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  JOBSHEET_CREATED = 'JOBSHEET_CREATED',
  JOBSHEET_COMPLETED = 'JOBSHEET_COMPLETED',
  WARRANTY_REMINDER = 'WARRANTY_REMINDER',
  CUSTOM = 'CUSTOM'
}

export enum SMSStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING'
}

// Product Returns
export enum ReturnSourceType {
  SALE = 'SALE',
  WARRANTY_CLAIM = 'WARRANTY_CLAIM',
  JOB_SHEET = 'JOB_SHEET',
  STOCK_CHECK = 'STOCK_CHECK',
  DIRECT = 'DIRECT',
  GOODS_RECEIPT = 'GOODS_RECEIPT'
}

export enum ReturnCategory {
  CUSTOMER_RETURN = 'CUSTOMER_RETURN',
  WARRANTY_RETURN = 'WARRANTY_RETURN',
  DEFECTIVE = 'DEFECTIVE',
  EXCESS_STOCK = 'EXCESS_STOCK',
  QUALITY_FAILURE = 'QUALITY_FAILURE',
  DAMAGED = 'DAMAGED',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER'
}

export enum ProductCondition {
  NEW_SEALED = 'NEW_SEALED',
  NEW_OPEN_BOX = 'NEW_OPEN_BOX',
  USED_EXCELLENT = 'USED_EXCELLENT',
  USED_GOOD = 'USED_GOOD',
  USED_FAIR = 'USED_FAIR',
  DEFECTIVE = 'DEFECTIVE',
  DAMAGED = 'DAMAGED',
  PARTS_MISSING = 'PARTS_MISSING',
  DESTROYED = 'DESTROYED'
}

